# Generated by Django 3.2.5 on 2022-11-06 12:44

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import reg_form.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HSC_Institute_name', models.CharField(max_length=50)),
                ('HSC_Board', models.CharField(max_length=20)),
                ('score_in_HSC', models.FloatField(max_length=30)),
                ('SSC_Institute_name', models.CharField(max_length=50)),
                ('SSC_board', models.CharField(max_length=30)),
                ('score_SSC', models.FloatField(max_length=30)),
                ('Currently_pursuing', models.CharField(blank=True, max_length=30)),
                ('Current_education_institution_name', models.CharField(blank=True, max_length=30)),
                ('Overall_percentage', models.FloatField(blank=True, max_length=30, null=True)),
                ('current_backlog', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('fathernamelast', models.CharField(blank=True, max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('mothernamelast', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('home_Address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('telephone_home', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('telephone_mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='img', validators=[reg_form.models.validate_image1], verbose_name='Image')),
                ('HSC_mark_sheet', models.FileField(upload_to='mark_hsc', validators=[reg_form.models.validate_image1])),
                ('SSC_mark_sheet', models.FileField(upload_to='mark_ssc', validators=[reg_form.models.validate_image1])),
                ('all_semesters_mark_sheet', models.FileField(upload_to='all_mark', validators=[reg_form.models.validate_multy])),
            ],
        ),
    ]
